name: Dagger Build for Clojure Web Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dagger-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install Dagger CLI
        uses: dagger/dagger-for-github@v7
        with:
          version: "0.15.4"

      - name: Build and test with Dagger
        working-directory: ./ci
        run: |
          go mod tidy
          go run main.go build-clj-web-app --src-dir ../my-app
